# author: Gael Lopes Da Silva
# project: Runned
# github: https://github.com/Gael-Lopes-Da-Silva/YellowedHelix

# syntax
"attribute"                       = { fg = "function", modifiers = ["bold"] }
"type"                            = { fg = "text" }
"type.builtin"                    = { fg = "keywords" }
"type.enum"                       = { fg = "keywords" }
"constructor"                     = { fg = "text", modifiers = ["bold"] }
"constant"                        = { fg = "constants", modifiers = ["bold"] }
"constant.builtin"                = { fg = "constants", modifiers = ["bold"] }
"constant.character"              = { fg = "string" }
"constant.character.escape"       = { fg = "constants", modifiers = ["bold"] }
"constant.numeric"                = { fg = "keywords" }
"string"                          = { fg = "string" }
"string.regexp"                   = { fg = "constants" }
"comment"                         = { fg = "comment" }
"variable"                        = { fg = "text" }
"variable.builtin"                = { fg = "keywords" }
"variable.parameter"              = { fg = "text", modifiers = ["italic"] }
"variable.other"                  = { fg = "text" }
"label"                           = { fg = "text" }
"punctuation"                     = { fg = "text" }
"punctuation.special"             = { fg = "constants", modifiers = ["bold"] }
"punctuation.delimiter"           = { fg = "text" }
"punctuation.bracket"             = { fg = "text" }
"keyword"                         = { fg = "keywords", modifiers = ["bold"] }
"keyword.control"                 = { fg = "keywords" }
"keyword.control.return"          = { fg = "keywords", modifiers = ["bold"] }
"keyword.operator"                = { fg = "keywords" }
"keyword.directive"               = { fg = "keywords", modifiers = ["bold"] }
"keyword.function"                = { fg = "keywords", modifiers = ["bold"] }
"operator"                        = { fg = "keywords" }
"function"                        = { fg = "function", modifiers = ["bold"] }
"tag"                             = { fg = "keywords", modifiers = ["bold"] }
"namespace"                       = { fg = "text" }
"special"                         = { fg = "keywords" }

"markup.heading.marker"           = { fg = "keywords", modifiers = ["bold"] }
"markup.heading.1"                = { fg = "text", modifiers = ["bold"] }
"markup.heading.2"                = { fg = "text", modifiers = ["bold"] }
"markup.heading.3"                = { fg = "text", modifiers = ["bold"] }
"markup.heading.4"                = { fg = "text", modifiers = ["bold"] }
"markup.heading.5"                = { fg = "text", modifiers = ["bold"] }
"markup.heading.6"                = { fg = "text", modifiers = ["bold"] }
"markup.list"                     = { fg = "keywords", modifiers = ["bold"] }
"markup.bold"                     = { modifiers = ["bold"] }
"markup.italic"                   = { modifiers = ["italic"] }
"markup.link.url"                 = { fg = "text", modifiers = ["underlined"] }
"markup.link.text"                = { fg = "string" }
"markup.quote"                    = { fg = "text" }
"markup.raw"                      = { fg = "string" }

# interface
"diff.plus"                       = { fg = "green" }
"diff.minus"                      = { fg = "red" }
"diff.delta"                      = { fg = "blue" }
"diff.delta.moved"                = { fg = "light_gray" }

"ui.background"                   = { bg = "gray", fg = "white" }
"ui.background.separator"         = { fg = "white" }
"ui.cursor"                       = { bg = "yellow", fg = "black" }
"ui.cursor.normal"                = { bg = "yellow", fg = "black" }
"ui.cursor.insert"                = { bg = "yellow", fg = "black" }
"ui.cursor.select"                = { bg = "yellow", fg = "black" }
"ui.cursor.match"                 = { bg = "smoke" }
"ui.cursor.primary"               = { bg = "yellow", fg = "black" }
"ui.cursor.primary.normal"        = { bg = "yellow", fg = "black" }
"ui.cursor.primary.insert"        = { bg = "yellow", fg = "black" }
"ui.cursor.primary.select"        = { bg = "yellow", fg = "black" }
"ui.debug.breakpoint"             = { fg = "red" }
"ui.debug.active"                 = { fg = "green" }
"ui.gutter"                       = { fg = "light_gray" }
"ui.gutter.selected"              = { fg = "light_gray" }
"ui.highlight.frameline"          = { fg = "gray" }
"ui.linenr"                       = { fg = "smoke" }
"ui.linenr.selected"              = { fg = "yellow", modifiers = ["bold"] }
"ui.statusline"                   = { fg = "white", bg = "dark_gray", modifiers = ["bold"] }
"ui.statusline.inactive"          = { fg = "light_gray", bg = "dark_gray" }
"ui.statusline.normal"            = { bg = "light_gray", modifiers = ["bold"] }
"ui.statusline.insert"            = { bg = "green", modifiers = ["bold"] }
"ui.statusline.select"            = { bg = "purple", modifiers = ["bold"] }
"ui.statusline.separator"         = { fg = "gray" }
"ui.popup"                        = { bg = "dark_gray", fg = "white" }
"ui.popup.info"                   = { bg = "dark_gray", fg = "white" }
"ui.window"                       = { fg = "white" }
"ui.help"                         = { fg = "white", bg = "dark_gray" }
"ui.text"                         = { fg = "white" }
"ui.text.focus"                   = { bg = "light_gray" }
"ui.text.inactive"                = { fg = "white" }
"ui.text.info"                    = { fg = "white", modifiers = ["bold"] }
"ui.virtual.ruler"                = { bg = "light_gray" }
"ui.virtual.whitespace"           = { fg = "light_gray" }
"ui.virtual.indent-guide"         = { fg = "smoke" }
"ui.virtual.inlay-hint"           = { fg = "light_gray" }
"ui.virtual.inlay-hint.parameter" = { fg = "light_gray" }
"ui.virtual.inlay-hint.type"      = { fg = "light_gray" }
"ui.virtual.wrap"                 = { fg = "light_gray" }
"ui.menu"                         = { fg = "white", bg = "dark_gray" }
"ui.menu.selected"                = { fg = "white", bg = "gray", modifiers = ["bold"] }
"ui.menu.scroll"                  = { fg = "light_gray", bg = "dark_gray" }
"ui.selection"                    = { bg = "smoke" }
"ui.selection.primary"            = { bg = "smoke" }
"ui.highlight"                    = { bg = "light_gray" }
"ui.cursorline.primary"           = { bg = "light_gray" }
"ui.cursorline.secondary"         = { bg = "light_gray" }
"ui.cursorcolumn.primary"         = { bg = "light_gray" }
"ui.cursorcolumn.secondary"       = { bg = "light_gray" }

"warning"                         = { fg = "warning", modifiers = ["bold"] }
"error"                           = { fg = "error", modifiers = ["bold"] }
"info"                            = { fg = "info", modifiers = ["bold"] }
"hint"                            = { fg = "hint", modifiers = ["bold"] }

"diagnostic.warning"              = { underline = { color = "warning", style = "curl" } }
"diagnostic.error"                = { underline = { color = "error", style = "curl" } }
"diagnostic.info"                 = { underline = { color = "info", style = "curl" } }
"diagnostic.hint"                 = { underline = { color = "hint", style = "curl" } }

[palette]
# interface
gray         = "#1F1F1F"
dark_gray    = "#181818"
light_gray   = "#303030"
smoke        = "#565656"
yellow       = "#FFD900"
purple       = "#994C92"
blue         = "#008DFF"
warning      = "#FF9C00"
error        = "#FF0000"
info         = "#0092FF"
hint         = "#4DFF00"

# syntax
text         = "#FFFFFF"
comment      = "#6B6B6B"
string       = "#378B1D"
constants    = "#FF80F4"
keywords     = "#FFD900"
function     = "#9B9B9B"
